[package]
name = "phoenix-escrow"
version = "1.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
cosmwasm-std = { version = "3.0.4", features = ["staking"] }
cw-storage-plus = "3.0.1"
cw2 = "3.0.0"
schemars = "1.2.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.18"
cw-utils = "3.0.0"
cosmwasm-schema = "3.0.4"

[dev-dependencies]
cosmwasm-schema = { version = "3.0.3" }

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[profile.release.build-override]
opt-level = 3
