#!/bin/bash
echo "=== INSTANTIATING AUCTION CONTRACT ==="
echo "After deployment, run:"
echo ""
echo "cored tx wasm instantiate <CODE_ID> '{}' \\"
echo "  --from testcore1tymxlev27p5rhxd36g4j3a82c7uucjjz4xuzc6 \\"
echo "  --label 'Phoenix Auction' \\"
echo "  --chain-id coreum-testnet-1 \\"
echo "  --node https://full-node.testnet-1.coreum.dev:26657 \\"
echo "  --gas auto --gas-adjustment 1.5 --fees 150000utestcore \\"
echo "  --no-admin --yes --broadcast-mode sync"
echo ""
echo "Then test it:"
echo "cored tx wasm execute <CONTRACT_ADDRESS> '{\"place_bid\":{\"amount\":100}}' \\"
echo "  --from testcore1tymxlev27p5rhxd36g4j3a82c7uucjjz4xuzc6 \\"
echo "  --chain-id coreum-testnet-1 \\"
echo "  --node https://full-node.testnet-1.coreum.dev:26657 \\"
echo "  --gas auto --fees 50000utestcore --yes"
